services:
  redis:
    image: redis:latest
    platform: linux/arm64
  dnmonster:
    image: amouat/dnmonster:1.0
    platform: linux/arm64
  identidock:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - platform=linux/arm64
