version: '3.8'

services:

  redis:
    image: redis:3.0

  dnmonster:
    image: amouat/dnmonster:latest
    ports:
      - "8080:8080"

  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENV=DEV
    volumes:
      - ./app:/app
    depends_on:
      - dnmonster
      - redis

